name: Build & push Docker image

on:
  pull_request:
  push:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: mcdock

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile

          # Only push when it's a direct push to main
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}

          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

          cache-from: type=gha
          cache-to: type=gha,mode=max